# English internal direction. Narration is finalized before anchors are attached.
variants={
242:(2,'bạn mở nắp','Friend offers a capped pen over the registration form.','Mascot holds the uncapped pen above the form; the cap is set beside it.'),
243:(5,'Mái nhà ngay ngắn hơn','The pencil drawing still has a crooked roof line; eraser rests nearby.','The same roof line is corrected and straight, eraser crumbs nearby; preserve all other marks.'),
244:(2,'giữ trang giấy phẳng','Mascot holds the eraser above the extra pencil line.','Mascot rubs the extra line while holding the same sheet flat; line is partially erased.'),
247:(5,'Bạn được giải thích rồi tự gấp lại','Mascot holds the open paper while the completed sample rests beside it.','Mascot has reproduced the demonstrated fold on their own paper, teacher keeps hands away.'),
248:(3,'bạn lấy thêm chiếc đĩa','Friend shows a positive response symbol; third table place has no plate.','Mascot places a plate at the same third place; other place settings remain fixed.'),
249:(3,'giờ bạn có thể đóng túi','Neat paper stacks are complete on desk; work bag is open.','Mascot has closed the work bag beside the unchanged completed paper stacks.'),
252:(2,'bạn đặt dụng cụ xuống','Mascot holds tape dispenser above a finished box at packing table.','Tape dispenser rests safely on table as mascot stands for break.'),
253:(3,'Hai người nhìn cùng tài liệu','Email is selected with attachment icon visible but not opened.','The same attachment is open, displaying a simple document layout without incidental text.'),
254:(3,'trang tài liệu hiện ra','Document icon selected in folder, file not yet open.','Selected document is open with simple geometric content; folder remains behind.'),
260:(3,'người ấy thêm một nét cuối','Painter holds brush near one incomplete short stroke on canvas.','Painter has added that single stroke; preserve all other composition and colors.'),
267:(2,'rồi chờ máy khởi động','Mascot finger approaches power button on unpowered desktop computer.','Power light is on and monitor shows boot glow; finger has moved away.'),
268:(3,'Mình đã cất rồi','Mascot holds closed laptop just above open carrying bag.','Same laptop is visibly inside the bag, hand holds bag opening only.'),
269:(3,'rồi lấy ra','Friend touches vibrating crossbody bag, own phone still inside.','Friend holds the recovered phone outside the same bag; mascot phone stays on table.'),
270:(3,'bức ảnh hiện rõ','Finger smudge obscures part of tablet portrait, soft cloth held beside device.','Tablet surface clean and portrait unobscured; cloth rests beside device.'),
271:(2,'bắt đầu gõ tên của mình','Mascot has both hands poised over keyboard, practice entry field empty.','Mascot types and abstract marks appear in same practice field; no personal data.'),
273:(2,'màn hình bài học xuất hiện','Phone shows home screen with learning app icon selected.','Same phone now shows simple lesson tiles inside app, preserve hand and camera.'),
274:(2,'chờ quá trình tải hoàn tất','Map download progress ring is partial on phone.','Map download progress is complete with simple check icon; no invented app text.'),
275:(3,'đợi dấu lưu xong','Drawing app displays the completed image with save action pending.','Saved image thumbnail appears in destination folder beside same drawing app.'),
276:(5,'Tấm nhòe được xóa đúng lựa chọn','Blurry image selected beside sharp image, both still present.','Only sharp image remains in same gallery; blurry image has been removed.'),
277:(2,'bài nghe bắt đầu xuất hiện','Cursor over play button, finger poised above mouse button.','Finger presses mouse button and play control changes to pause symbol with lesson content visible.'),
279:(3,'Sau đó bạn dán vào ô thứ hai','Selected text remains in first box; second box empty.','Matching abstract line appears in second box, original remains in first; keep exact line shapes identical.'),
280:(5,'trang tải tiếp','Both devices show loading rings over lesson pages.','Both devices show fully loaded lesson tiles, same devices and framing.'),
285:(2,'rồi mới gửi lời hẹn đã soạn','Message draft remains in input field under generic recipient avatar.','Draft has moved to sent message bubble with check icon, same recipient avatar.'),
287:(2,'bạn chọn khi thực sự muốn phản hồi','Like icon is outlined and unselected under post, mascot finger poised.','Same like icon is filled and selected after tap; post content unchanged.'),
288:(5,'bạn mới cầm túi ra cửa','Two packed bags on floor beside chosen rail route map, travelers stand nearby.','Both travelers hold the same bags and face doorway; map remains on table.'),
290:(2,'Hai người đặt tờ giấy ngay ngắn','Paper map orientation does not match bridge landmark ahead.','Map rotated to match bridge landmark from travelers viewpoint, hands steady its edges.'),
303:(2,'rồi lấy vé ra','Receipt in mascot hand, ticket still peeks from small bag pocket.','Ticket is in mascot hand and receipt stored separately; bag pockets unchanged.'),
305:(3,'bạn giúp nhấc xuống','Correct ribboned suitcase rests on stationary collection shelf, two people hold its handle.','Same ribboned suitcase rests on floor with both travelers beside it, other suitcase unchanged.'),
309:(3,'người lái đưa xe vào gọn trong vạch','Car is stationary just before permitted bay, camera wide and no pedestrian in path.','Same car fully inside marked bay; pedestrian entrance remains completely clear.'),
311:(3,'hai người chọn đúng tầng','Elevator panel visible with permitted numeral 2 unlit, friend hand poised.','Same numeral 2 is selected and illuminated; suitcase and travelers unchanged.'),
313:(5,'Người bạn nhận cốc nước','Empty clean cup on table, jug upright beside mascot.','Cup now filled with water and offered to friend; jug set upright on table.'),
314:(3,'người ấy đặt giày','Friend stands on muddy entry mat wearing muddy shoes, empty tray beside mat.','Both muddy shoes rest on tray and friend stands clear; dirt has not spread into home.'),
321:(5,'Hai người đã nhìn thấy mặt nước','Travelers on pedestrian path before trees obscure the lake.','Same view advanced to viewpoint, lake now visible between trees; preserve travelers and bag.'),
331:(2,'Bạn đưa tay rảnh nhận chiếc cốc','Rear view: mascot right hand holds box, left hand empty; friend offers cup.','Same rear camera: cup now in mascot anatomical left hand, box still in right.'),
332:(1,'Người bạn quay cùng hướng','Mascot and friend face each other, both arms lowered, camera at side.','Friend has turned to face same direction as mascot; both arms still lowered, establish rear-oriented view.'),
335:(3,'Người bạn chọn chỗ trống bên sách','Book rests beside lamp, empty coaster on book opposite side, friend holds cup.','Cup rests on that coaster beside book, away from lamp and cable; book remains next to lamp.'),
336:(2,'bạn chỉ đúng khoảng trống ở giữa','Top view: cup left, pencil case right, book held over empty middle gap.','Same top view: book now in middle between cup and pencil case, outer objects unchanged.'),
339:(5,'hai người đi vào đúng đường','Rear view: both pause at correct corner with shop as landmark.','Both have moved a short way into the indicated left branch, shop remains at corner behind.'),
}
