from pathlib import Path
import json,csv,hashlib,re
p=Path(__file__).resolve().parents[2];out=Path(__file__).resolve().parent;m=json.loads((out/'manifest.json').read_text()); complete=all(x.get('revision')==2 for x in m)
alltext=['# 20 kịch bản thử phần mở đầu — bài 81–100','', 'Trạng thái: '+('đã nộp content revision 2, chờ duyệt.' if complete else 'bản đề xuất; xem trạng thái từng bài, chưa dùng thay revision đang chạy.'),'', 'Nhóm A: tình huống xảy ra ngay. Nhóm B: câu tiếng Anh dùng ngay. Chỉ thử cách mở và đoạn nối; chưa có bằng chứng hiệu quả sau đăng.','']
for x in m:
 n=x['number'];src=Path(x['content']) if x.get('revision')==2 else out/'proposals'/f'{n}.json';c=json.loads(src.read_text());old=json.loads((out/'before'/f'{n}.json').read_text());assert c['scenes'][2:]==old['scenes'][2:]
 x['opening_after']=c['scenes'][0]['narration'];x['content_sha256']=hashlib.sha256(src.read_bytes()).hexdigest()
 lines=[f"# {n}. {x['word']} — nhóm {x['group']}",'',f"Job: `{x['job']}`. Trạng thái: {x['state']}. Revision: {x.get('revision','chưa nộp')}. Thời lượng dự kiến: {x['estimated_seconds']} giây; chưa đo WAV.",'']
 if x.get('review'):lines+=['[Bản duyệt content revision 2]('+x['review']+')','']
 lines+=['## Mở đầu trước và sau','','**Trước:** '+old['scenes'][0]['narration'],'','**Sau:** '+c['scenes'][0]['narration'],'','## Kịch bản đầy đủ','']
 for sc in c['scenes']:
  lines += [f"### {sc['id']} — {sc['title']}",'',sc['narration'],'',f"Khoảng chờ cuối cảnh: {sc['audio_direction']['vi']['learner_pause_seconds']} giây.",'','Hình dự kiến: '+sc['action'],'']
  if sc['id']=='SC01':lines+=['Biến thể giữ góc máy: '+sc['images'][1]['change'],'','Chữ cho phép: '+', '.join(i['text'] for i in sc['images'][0]['visible_text']),'']
 path=out/'readers'/f"{n}-{x['word'].replace(' ','-')}.md";path.write_text('\n'.join(lines)+'\n');x['reader']=str(path);alltext+=lines+['---','']
(out/'KICH-BAN-20.md').write_text('\n'.join(alltext)+'\n');(out/'manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
A=[x for x in m if x['group']=='A'];B=[x for x in m if x['group']=='B'];order=[v for pair in zip(A,B) for v in pair]
with (out/'THEO-DOI-SO-LIEU.csv').open('w',newline='') as f:
 writer=csv.writer(f);writer.writerow(['thu_tu_goi_y','so_bai','tu','nhom','job','content_revision','url_bai_dang','ngay_gio_dang','thoi_luong_thuc_giay','moc_do_24h_72h','luot_xem','giu_chan_2s_phan_tram','giu_chan_3s_phan_tram','giu_chan_5s_phan_tram','xem_trung_binh_giay','xem_het_phan_tram','luot_luu','chia_se','follower_moi','ghi_chu'])
 for k,x in enumerate(order,1):
  for milestone in ['24h','72h']:writer.writerow([k,x['number'],x['word'],x['group'],x['job'],x.get('revision',''),'', '', '',milestone]+['']*10)
lines=['# Lô thử phần mở đầu: 20 bài đủ điều kiện sửa','', '## Trạng thái','', ('20/20 bài đã tạo content revision 2, chờ duyệt. Media/video vẫn pending.' if complete else 'Đã soạn 20 bản đề xuất. Chưa hoàn tất nộp tất cả revision; xem manifest.json.'),'', 'Phạm vi: bài 81–100, heart đến meat, thuộc bộ 60 kịch bản. Bài 21–40 bị lệch integrity được giữ nguyên. Không tạo job mới, không sửa file được bảo vệ, không tạo âm thanh, ảnh hoặc video. Không coi xác nhận chốt revision 1 trước đây là duyệt revision 2.','', '## Cách sửa','', '- 10 bài A mở bằng tình huống; 10 bài B mở bằng câu tiếng Anh dùng ngay.','- Sửa SC01–SC02 và dữ liệu hình/neo liên quan. Thêm một biến thể có based_on ở SC01 để thể hiện hành động tiếp theo, giữ góc máy và mascot.','- Giữ nguyên toàn bộ SC03–SC05: ví dụ tiếp theo, thực hành, khoảng chờ và đáp án. Giữ brief, một nghĩa từ và hai câu ví dụ khác nhau.','- Mốc khoảng 61–66 giây là dự kiến từ tốc độ trong brief, chưa phải thời lượng âm thanh thật. Không dùng 256 ký tự làm trần sáng tạo.','', '## Đọc và duyệt','', '[Toàn bộ 20 kịch bản](KICH-BAN-20.md) · [Bảng theo dõi 24h/72h](THEO-DOI-SO-LIEU.csv)','', '| Bài | Từ | Nhóm | Bản đọc | Bản duyệt |','|---|---|---|---|---|']
for x in m:lines.append(f"| {x['number']} | {x['word']} | {x['group']} | [Kịch bản]({x['reader']}) | "+(f"[r2]({x['review']})" if x.get('review') else 'chưa nộp')+' |')
lines+=['','## Cách dùng số liệu','', 'Bảng CSV gợi ý đăng xen kẽ A/B; thời điểm đăng do người dùng chọn, cố gắng phân bố hai nhóm vào các khung tương đương. Điền đúng thời lượng MP4 và URL thật; giữ ô trống nếu nền tảng không hiển thị chỉ số. Đọc số liệu ở cùng mốc 24h và 72h.','', 'So sánh giữ chân sớm, thời gian xem trung bình, tỷ lệ xem hết có xét thời lượng; lượt lưu và follower chỉ là tín hiệu phụ khi mẫu nhỏ. Đối chiếu trung vị của nhiều bài mỗi nhóm, không chọn cách thắng từ một video. Khác chủ đề và người tiếp cận nên đây là thử nghiệm thăm dò, không phải A/B có kiểm soát. So với lô trước cũng thay cả phần mở và hình nên không tách riêng tác dụng của từng yếu tố.','', 'Tệp mục tiêu người Việt học cơ bản là giả thuyết từ brief, chưa phải chân dung đã xác minh từ analytics. Chưa có số liệu của lô thử, chưa khẳng định tăng giữ chân.','', '## Trước render','', 'Duyệt đúng content revision 2 từng bài trước media; sau đó tạo và kiểm tra âm thanh/ảnh thật, duyệt media rồi mới render và duyệt video. Lượt này chỉ tạo kịch bản.']
(out/'README.md').write_text('\n'.join(lines)+'\n');print('Exported',len(m),'readers; complete=',complete)
