from pathlib import Path
import json,sqlite3,hashlib,sys
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'reports/drama-A1-pilot-20261001';JOB='vocab-wait-for-script-738';folder=ROOT/'runs'/JOB
meta=json.loads((folder/'brief-current.json').read_text());b=json.loads((folder/f"briefs/{meta['revision']}.json").read_text())
frozen_path=OUT/'authoring/loi-dan-da-chot.json';frozen=json.loads(frozen_path.read_text());before_hash=hashlib.sha256(frozen_path.read_bytes()).hexdigest()
old=json.loads((OUT/'content-before-r2.json').read_text());mascot=old['characters'][0]
characters=[mascot,{'id':'CH02','name':'Mẹ','appearance':'Middle-aged fictional mother, minimal ink stick figure with a round white face, solid black oval eyes, modest small hair bun and simple expressive eyebrows. Ordinary proportions. Consistent face and hair in every scene. No realistic muscles or anime eye whites.','outfit':'Exactly one plain mustard-yellow short-sleeve top, minimal stick limbs. Carry the same small unmarked dark canvas travel bag. Rain on the top is an arrival detail; keep its color and silhouette.'},{'id':'CH03','name':'Bác tài','appearance':'Fictional adult bus driver in minimal ink stick style, round white face and solid black oval eyes. Plain small cap, ordinary proportions and consistent appearance.','outfit':'Exactly one plain lavender short-sleeve top and plain dark cap; no logos, badges, writing or extra torso.'}]
plans=[
 ('SC01','Establish a personal contradiction through the absent mother, two cups and an empty seat; no teaching title card.',['R1'],'The son disregards his mother\'s advice because he wants to see her before departure. The driver\'s warning makes that choice urgent.'),
 ('SC02','Make the first English utterance a real answer to the driver and show whom the son is waiting for.',['R2','R3'],'The driver warns that the bus is leaving; the son continues waiting, and the next shot reveals why the mother was delayed.'),
 ('SC03','Resolve the opening instruction and show maternal care through the tea exchange.',['R1','R2'],'The mother arrives after her last shift, takes the tea, and worries about her son eating. Now the immediate obstacle is saying goodbye.'),
 ('SC04','Offer the second English model as an unspoken thought caused by the mother turning toward departure.',['R3'],'The son cannot voice his farewell. As the mother nears the bus door, the audience can help him recall the line he needs.'),
 ('SC05','Invite completion of the same meaningful line, then hold without revealing the answer during the learner interval.',['R4'],'Hold for four seconds after the incomplete sentence. The next scene gives the full answer and shows its consequence.'),
 ('SC06','Give the answer, show the embrace and close this departure with a changed meaning for the son\'s waiting.',['R2','R4'],'The mother pauses for the embrace, then leaves. The son\'s own tea is cold; waiting now means the hope of her return. This episode resolves its initial promise.')
]
outline=[dict(scene_id=sid,purpose=purpose,requirements=req,transition=transition) for sid,purpose,req,transition in plans]
(OUT/'outline-planned.json').write_text(json.dumps({'outline':outline},ensure_ascii=False,indent=2)+'\n')
# All narration was frozen before creating image/beat anchors and coverage below.
common=' Attach the canonical Character reference for the mascot. Keep a single pale-blue short-sleeve torso, round white navy-outlined head, solid black oval eyes and minimal stick limbs. Off-white minimal ink world. Use only the listed people. No incidental text, numbers, logos or watermarks. Keep outer ten percent and bottom twenty-two percent clear for captions/UI; only permitted visible_text may appear.'
placement='Upper third, within the central safe region and separate from faces. A short readable line at phone size; bottom subtitle region remains clear.'
def text(t):return {'text':t,'placement':placement,'object':'Flat learning caption with a quiet off-white backing, no additional wording.'}
def image(sid,i,description,chars,why,texts=(),base=None,preserve=''):
 return dict(id=f'{sid}_I{i}',description=description+common,character_ids=chars,based_on=base,preserve=preserve,change=description,reason=why,visible_text=[text(t) for t in texts])
shot_data=[
 ('Exterior bus shelter at dusk; same bench left of bus door, same unmarked bus on frame right.', 'Medium close shot at cup and torso height. Son and two cups dominate; the empty neighboring place is plainly visible. No cold-open title.','The mascot waits with exactly two identical white lidded paper tea cups, one in each hand; mother has not arrived. An empty bench seat is beside him.', ['CH01'], [
  ('The mascot son at the bus shelter, head slightly lowered, exactly two identical white lidded paper tea cups, one in each hand. The neighboring bench seat is empty. The unmarked bus door is at frame right. No mother and no passenger crowd.',['CH01'],'Show the discrepancy between two drinks and one waiting person immediately.',[],None,'')], [frozen[0]['narration']], [0.5,0.43]),
 ('Same bus shelter and unmarked bus at dusk.', 'Medium two-shot; driver points toward the bus entrance while the son keeps both cups. Keep the dialogue caption in the same upper safe region.','The driver warns the son that the bus will leave. The son still holds both cups and waits for his absent mother.', ['CH01','CH03'], [
  ('At the same shelter, the mascot son holds both white paper tea cups while the lavender-shirted capped driver gestures once toward the bus entrance at frame right. Mother is absent; keep the neighboring bench place empty.',['CH01','CH03'],'Connect the son\'s answer with the missing person and the immediate departure deadline.', ["I'm waiting for my mum.",'wait for · chờ đợi'],None,'')], [frozen[1]['narration']],[0.5,0.4]),
 ('Same bench and bus door; light rain has just stopped.', 'Stable medium two-shot, mother entering from frame left. For the tea handoff keep the same axis, scale and background.','Mother arrives with her canvas travel bag after the last work shift. The son hands her one cup; she receives it with both hands.', ['CH01','CH02'], [
  ('The mustard-shirted mother with her small dark canvas travel bag has just reached her pale-blue-shirted adult son at the shelter. Light rain marks on her top; keep its mustard color. He still holds exactly two white paper tea cups. Mother has not taken a cup yet. The unmarked bus waits at frame right.',['CH01','CH02'],'Pay off the mother\'s absence before the farewell; show that she did come.',[],None,''),
  ('From the same view, the mother now holds one white paper cup with both hands. The son retains the other cup. Her travel bag rests by her feet. Her small concerned head tilt toward her son shows her last practical advice before departure.',['CH01','CH02'],'Show a tangible caring gesture and preserve the before/after tea transfer.',[],'SC03_I1','Keep the camera, bench, bus entrance at frame right, both identities and outfits, bag location, lighting, cup designs and total of exactly two cups. Change only who holds the mother\'s cup and the small gestures.')], [frozen[2]['narration'].split(' Tôi đưa trà.')[0],'Tôi đưa trà.'],[0.5,0.4]),
 ('Same shelter; bus entrance still frame right.', 'Medium two-shot at first, then close on the son\'s raised free hand and tilted face; preserve bus direction and show the mother\'s shoulder turning away.','Mother turns toward the bus, carrying her travel bag and tea. The son has one cup and cannot speak; he starts raising his free hand.', ['CH01','CH02'], [
  ('Mother in mustard turns away toward the bus entrance at frame right, holding her single tea cup and carrying the same canvas bag. The pale-blue mascot son remains near the bench with his own cup, shoulders slightly inward, as if the farewell catches in his throat. They are still close enough to speak.',['CH01','CH02'],'Show the obstacle changing from waiting to being unable to ask for one more moment.',[],None,''),
  ('A tighter composition along the same axis: the son holds his own single cup in one hand and raises the free hand toward his mother. Her mustard shoulder and canvas bag are visible nearer the bus entrance at frame right. He has not yet spoken; no dialogue bubble tail implying the model has already been said aloud.',['CH01','CH02'],'Give the silent thought a legible model and a specific communicative purpose.', ['Please wait for me.'],None,'')], [frozen[3]['narration'].split(' Trong đầu')[0],'Trong đầu chỉ còn một câu:'],[0.5,0.4]),
 ('Same shelter, mother just outside the bus entrance.', 'Stable medium shot with one incomplete English line. Hold the same image during the four-second learner turn, no countdown or answer leak.','Mother is at the entrance but has not boarded. The son\'s free hand is raised; the missing phrase can still make her stop.', ['CH01','CH02'], [
  ('Mother with one tea cup and her small canvas travel bag stands just outside the unmarked bus entrance at frame right, turned partly away. The mascot son stays in the shelter with his own cup and a raised free hand. This is the suspended moment before he calls. Do not show the completed answer, other writing or a countdown.',['CH01','CH02'],'Let the viewer supply the useful missing phrase and keep the emotional situation suspended.', ['Please ... me.'],None,'')], [frozen[4]['narration']],[0.5,0.4]),
 ('Same shelter; bus subsequently departs toward frame right.', 'Medium close on the embrace and answer, then a separate wider aftermath of the son alone at the bench; hold the final image without a generic CTA.','The son finally calls. Mother turns back for an embrace, then takes her cup and bag onto the bus. The bus leaves and the son remains with only his own now-cold cup.', ['CH01','CH02'], [
  ('At the shelter mother has turned back to embrace her pale-blue-shirted adult son. Each still has exactly one white paper cup, kept safely at the outside of the embrace; their bodies each have exactly one torso. The small canvas bag rests beside the mother. The bus waits at frame right. Minimal inward head tilt and relaxed shoulders, no exaggerated crying or realistic anatomy.',['CH01','CH02'],'Answer the learner turn and show that asking bought the farewell embrace.', ['Please wait for me.'],None,''),
  ('A wider aftermath: the mascot son sits alone at the same bench holding only his own single white paper tea cup. His shoulders are lower, gaze toward the unmarked bus receding at frame right; his mother and her cup are now on that bus and are not visible in the shelter. No extra cup left on the bench, no driver or new people. Quiet dusk and generous empty space.',['CH01'],'Close the local story and make the cold cup an emotional callback to the first two cups.',[],None,'')], ['"Please wait for me."','Xe rời bến.'],[0.5,0.43])
]
scenes=[]
for frozen_sc,plan,shots in zip(frozen,plans,shot_data):
 sid,purpose,req,transition=plan;setting,camera,action,chars,im_specs,anchors,focus=shots
 images=[image(sid,i,*spec) for i,spec in enumerate(im_specs,1)]
 beats=[{'id':f'{sid}_B{i}','image_id':im['id'],'purpose':im['reason'],'anchor':{'vi':{'quote':q,'occurrence':1}},'effect':'hold' if sid=='SC05' else 'cut','focus':{'x':focus[0],'y':focus[1]}} for i,(im,q) in enumerate(zip(images,anchors),1)]
 intent={'SC01':'Tell a restrained personal memory; the mother\'s advice is the immediate point of attention.','SC02':'Answer the driver with a clear English line, then let the departure warning create urgency.','SC03':'Reveal the mother\'s reason for lateness, then convey care through ordinary advice; avoid melodramatic sobbing.','SC04':'Convey an unspoken thought and an English request; do not claim the engine supports a separate actor voice.','SC05':'Invite the listener to complete the request compassionately, then leave four seconds of quiet.','SC06':'Give the complete answer clearly, then close with a restrained farewell and the cold-tea callback.'}[sid]
 scenes.append({'id':sid,'title':frozen_sc['title'],'purpose':purpose,'action':action,'setting':setting,'camera':camera,'narration':frozen_sc['narration'],'requirements':req,'character_ids':chars,'source_ids':[],'vocabulary':[{'word':'wait for','meaning':'chờ đợi'}],'images':images,'beats':beats,'audio_direction':{'vi':{'intent':intent,'pronunciation_notes':'Keep I and all English spelling intact. Audition the actual WAV for waiting for, my mum, wait for me, language switches and the scene-tail learner interval. These notes do not set engine emotion or add a separate voice.','learner_pause_seconds':4 if sid=='SC05' else 0}}})
coverage=[]
for req,sid,q in [('R1','SC01',frozen[0]['narration']),('R2','SC02','"I\'m waiting for my mum." Tôi đang chờ mẹ.'),('R3','SC02','"I\'m waiting for my mum."'),('R3','SC04','"Please wait for me." Chờ con với.'),('R4','SC05',frozen[4]['narration']),('R4','SC06','"Please wait for me." Chờ con với.')]:coverage.append({'requirement_id':req,'scene_id':sid,'quote':q})
with sqlite3.connect(f'file:{ROOT}/.state/jobs.sqlite?mode=ro',uri=True) as db:requests=db.execute("SELECT id,detail FROM events WHERE job=? AND module='content' AND event='rejected' ORDER BY id",(JOB,)).fetchall()
assert requests[-1][1]==(OUT/'user-request.txt').read_text().strip()
responses=[{'request_id':str(rid),'status':'addressed','explanation':('Yêu cầu trước đã được xử lý tại content r2. Theo yêu cầu mới, bản thử thay cả diễn biến lớp thủ công bằng lần tiễn mẹ; tiếp tục giữ mở ngắn, một nghĩa, hai mẫu, lượt thực hành và phản hồi.' if i<len(requests)-1 else 'Viết lại sáu cảnh thành một tập drama hư cấu: câu đầu ngắn, hai ly trà/chỗ trống, áp lực xe sắp chạy, trả lời vì sao mẹ muộn, hai mẫu tiếng Anh có nhu cầu, điền câu/chờ 4 giây, cái ôm và trà nguội. Giữ mascot, nghĩa kho và R1–R4. Chưa tạo media hay đo giữ chân.'),'scene_ids':['SC01','SC02','SC03','SC04','SC05','SC06']} for i,(rid,note) in enumerate(requests)]
c={'schema_version':'3.0','brief_revision':meta['revision'],'brief_hash':meta['hash'],'topic':b['topic'],'duration':b['duration'],'style':b['style'],'required_points':[r['text'] for r in b['required_points']],'characters':characters,'scenes':scenes,'coverage':coverage,'outline':outline,'claims':[],'revision_response':responses,'open_questions':[]}
assert before_hash==hashlib.sha256(frozen_path.read_bytes()).hexdigest()
for sc in scenes:
 for bt in sc['beats']:assert bt['anchor']['vi']['quote'] in sc['narration']
for cv in coverage:assert cv['quote'] in next(s['narration'] for s in scenes if s['id']==cv['scene_id'])
(OUT/'candidate.json').write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n');(folder/'draft/content.json').write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n');(folder/'draft/outline.json').write_text(json.dumps({'outline':outline},ensure_ascii=False,indent=2)+'\n')
print('Built six-scene trial from frozen narration:',sum(len(s['images']) for s in scenes),'planned images; brief',meta['revision'],'feedback',len(responses))
