import json,sys,pathlib,time,traceback
root=pathlib.Path('/home/hongphuoc6104/Desktop/pipelineFlow'); sys.path.insert(0,str(root/'sys'))
from scripts.agy_pipeline import invoke
base=root/'sys/reports/drama-A1-all-20261001'; own=base/'shards/nhom-2'
manifest=json.loads((base/'manifest.json').read_text());jobs=json.loads((base/'shard-assignments/nhom-2.json').read_text())['jobs']; idx={x['job']:x for x in manifest}
a=int(sys.argv[1]);n=int(sys.argv[2]) if len(sys.argv)>2 else 10
chosen=[idx[j] for j in jobs[a:a+n]]
out=own/f'attempt-{a:03}-{int(time.time())}';out.mkdir()
inputs=[]
for x in chosen:
 inputs.append({'job':x['job'],'entry_id':x['entry_id'],'word':x['word'],'pos':x['pos'],'gloss_vi':x['gloss_vi'],'scene_count':x['scene_count'],'required_points':x['brief']['required_points'],'avoid':x['brief']['planning']['avoid'],'original_narration':[s['narration'] for s in x['content']['scenes']]})
( out/'inputs.json').write_text(json.dumps(inputs,ensure_ascii=False,indent=2))
schema={'type':'object','properties':{'episodes':{'type':'array','minItems':len(chosen),'maxItems':len(chosen),'items':{'type':'object','required':['job','title','plot_vi','opening_function_vi','learner_outcome_vi','characters','scenes'],'properties':{'job':{'type':'string'},'title':{'type':'string'},'plot_vi':{'type':'string'},'opening_function_vi':{'type':'string'},'learner_outcome_vi':{'type':'string'},'characters':{'type':'array','items':{'type':'object','required':['id','name_vi','appearance_en','outfit_en'],'properties':{k:{'type':'string'} for k in ['id','name_vi','appearance_en','outfit_en']}}},'scenes':{'type':'array','items':{'type':'object','required':['scene_id','title_vi','narration','purpose_en','visual_en','character_ids','practice_pause_seconds'],'properties':{**{k:{'type':'string'} for k in ['scene_id','title_vi','narration','purpose_en','visual_en','stem']},'character_ids':{'type':'array','items':{'type':'string'}},'practice_pause_seconds':{'type':'number'},'extra_visual_states':{'type':'array','items':{'type':'object'}},'custom_visible_text':{'type':'array','items':{'type':'object'}}}}}}}}},'required':['episodes']}
prompt='''You are a vocabulary episode writing assistant. Return ONLY JSON episodes; do not call any tools, edit files, approve anything or generate media. No paid services, no account/model/provider change. Data below defines exact JOB, selected bank sense/POS, required points, existing scene count and sibling senses to AVOID. Original narration is evidence of intended sense only; replace the lecture with an original micro-drama.
Write polished natural VIETNAMESE spoken personal stories like a small ordinary want, resistance, action, consequence. Vary relationships, settings, openings and emotion across episodes. No dictionary lecture, stock motivational endings, CTA, greetings, ornate AI prose, repeated mother-departure/tea plot or forced tragedy. First sentence <=9 whitespace units, concrete action/contradiction/inner thought; no title. First usable simple English model in scene1 or early2. Exactly required number of English example models (usually2), plus repeat the retrieval answer later. Keep one sense ONLY and correctly support each model in Vietnamese, with accurate tense/referent. NEVER use noun login for verb: use log in.
Each episode: job,title,plot_vi,opening_function_vi,learner_outcome_vi,characters[{id,name_vi,appearance_en,outfit_en}], scenes[{scene_id,title_vi,narration,purpose_en,visual_en,character_ids,practice_pause_seconds}]. One learner scene must have stem with ___ replacing the TARGET keyword, not a different noun; invite full-sentence retrieval tied to same plot, 4 seconds quiet hold at the END, immediately NEXT scene gives full correct answer then payoff. Do not read incomplete stems/ellipses in narration. Keep exactly original scene_count (5/6/7); no anchors/coverage. Aim about130–170 Vietnamese whitespace units total for5 scenes, longer if needed for6/7. Build natural direct dialogue and earned small ending, no stock 'Đến lượt bạn thực hành', 'Đúng rồi', 'Tuyệt vời', 'bạn đã...' praise. Do not pad.
English instructions ONLY for purpose_en, visual_en, appearance_en,outfit_en. Vietnamese titles/plot/outcome/narration retain English models. CH01 always main canonical mascot: round white head/dark navy outline, two solid black oval eyes, exactly ONE single pale-blue #8CCFE8 short-sleeve torso, minimal stick limbs. Cast at most one essential secondary person (also minimal ink white head with solid oval eyes, one different plain top). Mascot can be older by a small hair cue, without losing canonical core. Every frame must show target meaning/action/relation, props/state/position continuous, concrete camera framing, not theme only, no internal IDs in visual prose. No realistic people/muscles, no doubling torso.
For essential state changes use scene.extra_visual_states:[{quote:literal fragment of narration,visual_en: same-camera before/after description,purpose_en:what relation to notice}]. Preserve exact quote. For any numerical values/names/screen/button text essential to meaning, use scene.custom_visible_text:[{text:exact permitted string,placement:English placement,object:English object}] then visual_en refer to exact permitted text only. No incidental readable text. Avoid unverifiable medicine/electricity/security/finance rules or universal claims. Grammar/meaning should be simple and accurate. Adjectives teach selected descriptive usage; verbs show actions; time/count/measurement nouns distinguish units with controlled marks when needed.
Do not mark editorial review or visual_review_ready: human-authorized agent will read and repair actual JSON before freezing.
INPUT DATA:\n'''+json.dumps(inputs,ensure_ascii=False)
prompt += '\nUse the following finished episode as a QUALITY REFERENCE: first-person natural modest drama, exact direct retrieval instruction, NO decorative adjectives/adverbs or description of how clearly the narrator speaks. Do not copy plot/lines, only the standard.\n' + (base/'narration-frozen/vocab-pen-script-242.json').read_text() + '\nAdditional reference of restrained personal narration and state planning:\n' + (base/'narration-frozen/vocab-week-script-456.json').read_text() + '\nBefore returning read and repair ALL your episodes: every practice narration must explicitly ask the VIEWER to say the full English sentence with Vietnamese meaning; every practice scene MUST have stem property, target keyword gap. Final narration starts with quoted full answer followed by small consequence; not saying I repeat clearly. Second model must be a useful action inside same evolving story, not unrelated fact. Give all requested jobs.'
(out/'prompt.txt').write_text(prompt)
try:
 r=invoke(prompt,schema,out,timeout=240)
 (out/'response.json').write_text(json.dumps(r,ensure_ascii=False,indent=2))
 print(json.dumps({'attempt':str(out),'count':len(r['structured_output']['episodes'])},ensure_ascii=False),flush=True)
except Exception as e:
 (out/'failure.txt').write_text(str(e));print(str(e),flush=True);sys.exit(1)
