# Frozen narration anchors and explicit state changes; all directives in English.
variants={
341:(1,'người bạn nhắc nhìn ký hiệu','Mascot holds map upright with compass arrow, house and lake icons fixed relative to paper.','Same map is rotated in mascot hands; compass arrow and icons rotate together, never independently.'),
342:(2,'rồi mới đặt quân','Lake icon fixed, house token held above correct south position marked by compass.','House token sits south of lake, compass and all other icons unchanged.'),
343:(3,'Bạn đặt hình công viên','Park token held above empty east position beside house icon.','Park token placed east of house as indicated by compass, hand withdraws.'),
350:(3,'Mặt trời giờ ở sau một đám mây.','Sun partly visible beside cloud above garden, desk lit indirectly.','Same cloud now covers sun, garden light softer; camera and house geometry fixed.'),
351:(2,'Bạn nhường vị trí sát cửa','Mascot stands at window where moon visible, friend at blocked angle behind.','Mascot steps aside and friend occupies clear window angle, moon remains above same roof.'),
353:(3,'bạn dùng màu xanh nhẹ','Landscape drawing has blank sky above fixed houses and trees.','Same sky area filled pale blue with white cloud gaps, lower drawing unchanged.'),
355:(5,'Bạn đặt ảnh vào album','Snowy footprints photo held above empty album slot.','Same photo inserted into slot, snowy image unchanged.'),
356:(3,'thả vào đúng cốc','Scoop holds a few ice cubes over selected empty glass.','Ice cubes now in selected glass, second glass unchanged, scoop withdrawn.'),
357:(2,'bạn đặt cuốn sách lên góc giấy','Paper corner lifts in window breeze, book held above one edge.','Book rests on paper corner and holds sheet flat, curtain still billows.'),
358:(3,'Hai người mang sách tới bàn đã chọn','Both stand at shaded table with closed books in hands.','Both seated at same shaded table with books open, sunlit courtyard unchanged.'),
360:(2,'bạn đặt bóng lại chỗ cũ','Mascot holds ball by rainy doorway, basket on dry indoor floor.','Ball now in basket, mascot turns toward indoor game table.'),
361:(3,'Hai người gấp bản đồ lại','Large map flaps between two friends in wind.','Same map folded to compact section and held securely; hat secured.'),
365:(2,'Bạn đặt cốc lên khăn lót','Mascot holds cold glass with condensation above coaster away from paper.','Same glass rests on coaster and hands withdraw; paper dry.'),
372:(3,'Hình con thỏ giúp kiểm tra dự đoán','Mascot holds rabbit silhouette card, full illustration still concealed.','Card turned to reveal full rabbit illustration with matching ears; hands and table stable.'),
373:(5,'Chiếc giường đã có chủ','Dog stands next to empty small pet bed, adults seated nearby.','Same dog curled on pet bed, bowl remains in place.'),
374:(2,'tới lấy chiếc dép nằm cạnh','Slipper lies beside relaxed dog bed, friend approaches slowly.','Friend holds slipper retrieved from floor; dog stays relaxed on bed.'),
376:(2,'Khi nó bước ra','Rabbit ears and part of face visible behind low shelter.','Whole rabbit visible outside same shelter, enclosure and visitors unchanged.'),
381:(3,'Tôi thấy ba con cừu.','One sheep fully visible and two partly behind open gate.','All three sheep fully visible side by side, same gate and fence.'),
382:(3,'Có hai con gà.','One chicken visible and second partly hidden behind bin.','Both chickens fully visible side by side, coop and bin unchanged.'),
384:(2,'Bạn đặt mảnh vào đúng chỗ','Lion-head puzzle piece held above matching empty space.','Piece seated correctly, complete male lion with mane now visible.'),
385:(2,'Người bạn kéo tờ giấy sang bên','Tiger body visible on card but head covered with blank paper.','Blank paper moved aside, complete tiger image visible; illustration unchanged.'),
387:(2,'Bạn ghép mảnh vòi','Trunk piece held beside elephant head with matching gap.','Trunk piece fitted, complete elephant illustration visible.'),
393:(3,'bạn đặt hai chiếc cạnh nhau','Friend holds two leaves above table separate from mascot original leaf.','Friends two leaves laid side by side; mascot original remains separate so count is unambiguous.'),
394:(2,'bọc phần thân','Florist holds unwrapped single rose by stem, paper on counter.','Same rose stem wrapped with bloom uncovered, bouquet remains separate.'),
396:(1,'Chiếc chậu giữ nguyên','First photograph: small young plant in familiar pot on same background.','Later photograph: same pot and setting, plant taller with additional leaves; indicate separate photos, not instantaneous growth.'),
397:(3,'Hai người gom hết phần còn lại','Wrappers and used paper remain on picnic table, waste bag held open.','Waste now in designated bag, reusable container retained separately, table clear.'),
398:(1,'người bạn giữ cho nó dừng lại','Mascot hand turns globe gently on stable stand.','Friend steadies globe at selected orientation, geography fixed on globe surface.'),
404:(3,'Tôi có hai điểm.','One scoring token for mascot on plain card.','Two tokens for mascot on same card, no other score changes.'),
407:(2,'người bạn dùng chân đưa bóng','Ball stationary beside friend foot, mascot ready opposite.','Friend foot has contacted ball and ball rolls toward mascot along ground; clear continuous trajectory.'),
408:(2,'bạn đưa bóng bằng tay','Mascot holds soft ball low, friend ready with hands open.','Ball just released from underhand throw in short low arc toward friend.'),
409:(2,'bạn đưa tay đúng tầm','Soft ball approaching mascot open hands at chest height.','Same ball secured between both hands in front of torso, friend remains same position.'),
410:(2,'cả hai nhìn mốc rồi mới bắt đầu','Both runners stand at start, cone ahead on clear path.','Both jog a short distance toward same cone, camera and lane direction stable.'),
411:(2,'bạn nhìn chỗ đặt chân','Mascot stands before chalk line with knees slightly bent.','Mascot mid small jump just above line, both feet airborne, landing area clear.'),
4110:(3,'Tôi có thể nhảy qua nó.','',''),
413:(3,'người bạn lấy ra','Ball partly under bench, friend kneels to retrieve.','Ball now in friend hands outside bench, mascot waiting nearby.'),
417:(5,'Chiếc vợt đúng đã được cho vào túi','Tennis racket beside open sports bag, table-tennis paddle separate.','Tennis racket inside bag with handle visible, small paddle still on table.'),
422:(3,'hai người thống nhất rồi mới bấm','Fictional movie selection thumbnails on screen, remote in mascot hand.','Chosen generic funny movie scene plays on same screen, thumbnail menu gone.'),
426:(2,'bấm bật','Television dark, friend holds remote toward device.','Television on with generic image, same camera and furniture.'),
427:(3,'chương trình mong chờ hiện ra','Television displays wrong generic program while friend holds remote.','Screen changes to desired fictional program, all room elements unchanged.'),
429:(2,'người bạn hạ xuống','Open newspaper hides friend face, mascot holds cup.','Newspaper folded lower, friend face visible, cup rests safely on table.'),
431:(3,'màn hình giữ bước gấp lại','Phone displays moving-step generic lesson with play-state icon.','Phone paused on specific fold with pause state, mascot replicates same fold on own paper.'),
432:(2,'rồi tháo ra','Camera lens cap still attached, mascot hand at its edge.','Cap removed and placed in pouch, clear lens visible.'),
436:(2,'người bạn bước sát vào khung hơn','Selfie preview has mascot and cropped friend shoulder.','Selfie preview now includes both full faces, phone distance and safe ground preserved.'),
438:(3,'người bạn lưu lại','Generic current song card not yet favorited, no real title.','Same song card has selected star icon in saved list.'),
}
variants.pop(4110)
