#!/usr/bin/env bash
set -euo pipefail
cd /home/hongphuoc6104/Desktop/pipelineFlow
if [[ ! -t 0 ]]; then
  echo "Hãy chạy file này trực tiếp trong terminal, không qua pipe hoặc heredoc." >&2
  exit 2
fi
# Chỉ người dùng chạy file này sau khi đã xem integrity-diff.
sys/.venv/bin/python pilot.py adopt-code vocab-toilet-55s-001 --confirm vocab-toilet-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-forget-55s-001 --confirm vocab-forget-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-remember-55s-001 --confirm vocab-remember-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-carry-55s-001 --confirm vocab-carry-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-late-55s-001 --confirm vocab-late-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-early-55s-001 --confirm vocab-early-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-wait-55s-001 --confirm vocab-wait-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-walk-55s-001 --confirm vocab-walk-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-cook-55s-001 --confirm vocab-cook-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-done-55s-001 --confirm vocab-done-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-busy-55s-001 --confirm vocab-busy-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-free-55s-001 --confirm vocab-free-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-get-dressed-55s-001 --confirm vocab-get-dressed-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-get-ready-55s-001 --confirm vocab-get-ready-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-family-55s-001 --confirm vocab-family-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-parent-55s-001 --confirm vocab-parent-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-mother-55s-001 --confirm vocab-mother-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-father-55s-001 --confirm vocab-father-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-mum-55s-001 --confirm vocab-mum-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-dad-55s-001 --confirm vocab-dad-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-son-55s-001 --confirm vocab-son-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-daughter-55s-001 --confirm vocab-daughter-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-child-55s-001 --confirm vocab-child-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-kid-55s-001 --confirm vocab-kid-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-baby-55s-001 --confirm vocab-baby-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-brother-55s-001 --confirm vocab-brother-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-sister-55s-001 --confirm vocab-sister-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-grandparent-55s-001 --confirm vocab-grandparent-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-grandmother-55s-001 --confirm vocab-grandmother-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-grandfather-55s-001 --confirm vocab-grandfather-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-uncle-55s-001 --confirm vocab-uncle-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-aunt-55s-001 --confirm vocab-aunt-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-cousin-55s-001 --confirm vocab-cousin-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-husband-55s-001 --confirm vocab-husband-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-wife-55s-001 --confirm vocab-wife-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-friend-55s-001 --confirm vocab-friend-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-best-friend-55s-001 --confirm vocab-best-friend-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-classmate-55s-001 --confirm vocab-classmate-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-boyfriend-55s-001 --confirm vocab-boyfriend-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-girlfriend-55s-001 --confirm vocab-girlfriend-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-love-55s-001 --confirm vocab-love-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-hate-55s-001 --confirm vocab-hate-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-visit-55s-001 --confirm vocab-visit-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-body-55s-001 --confirm vocab-body-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-head-55s-001 --confirm vocab-head-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-hair-55s-001 --confirm vocab-hair-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-face-55s-001 --confirm vocab-face-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-eye-55s-001 --confirm vocab-eye-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-nose-55s-001 --confirm vocab-nose-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-mouth-55s-001 --confirm vocab-mouth-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-tooth-55s-001 --confirm vocab-tooth-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-ear-55s-001 --confirm vocab-ear-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-neck-55s-001 --confirm vocab-neck-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-arm-55s-001 --confirm vocab-arm-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-hand-55s-001 --confirm vocab-hand-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-finger-55s-001 --confirm vocab-finger-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-back-55s-001 --confirm vocab-back-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-leg-55s-001 --confirm vocab-leg-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
sys/.venv/bin/python pilot.py adopt-code vocab-foot-55s-001 --confirm vocab-foot-55s-001 --reason 'Người dùng đã xem integrity-diff và chấp nhận bộ mã hiện tại để cập nhật kịch bản bài 22–80.'
echo "Đã mở chặn đủ 59 job. Chưa chạy content, âm thanh hoặc video."
