from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'reports/drama-A1-all-20261001';jobs=json.loads((OUT/'narration-attempts/004-015/episodes.json').read_text())['episodes']
visuals=[
['At an evening classroom door, the older mustard-shirted learner hesitates with a closed notebook. Pale-blue mascot points to the empty chalkboard and pulls out the front chair. No written literacy label or other pupils.', 'Inside the same room, mascot offers a chalk piece to the learner beside the chalkboard. The learner starts lifting a hand then holds it near the closed notebook, showing hesitation.', 'The learner follows a few non-letter practice strokes in one corner of the classroom board while mascot stands aside to leave room. One chalk piece, no readable extra word or name.', 'Hold learner and mascot facing the same classroom board with the practice marks. Leave top space for the sentence stem, no completed answer.', 'Learner makes one more chalk stroke and turns toward mascot as if asking to return tomorrow. The previously closed notebook is now held carefully and open; same room and board.'],
['A dark burnt pastry rests on a tray at the small bakery. Mascot hesitates with a raised hand; the mustard-shirted woman turns off the closed oven and pulls a chair near him. No flame or detailed cooking controls.', 'Mascot looks down at the same burnt tray, while the patient mentor sits nearby and listens. His small lowered head shows admitting that he did not understand, with no humiliation or angry pointing.', 'The mentor slides a plain blank note toward mascot, who now asks with an open hand. A new unbaked batch remains untouched on a separate tray; no baking ratio or technical instructions.', 'Hold mascot raising a hand to ask while mentor is paused mid-task and looking toward him. The new batch remains untouched; top stem only.', 'At the end of the same shift, mentor listens to mascot\'s question. Mascot then puts the plain note in his shirt-free pocket/bag area and leaves with a calmer pose. Keep one canonical torso.'],
['Mascot reads a message on a plain phone with blank screen, then lowers it face down beside a simple work schedule grid with no writing. Mother remains offscreen; no mother portrait or message text.', 'At the workplace desk, mascot asks the mustard-shirted male manager for a shift change, pointing to a plain blank grid. Manager listens; no dates, employee names or numbers visible.', 'Mascot alone holds the phone before making the call, rehearsing a clear answer with a small determined head tilt. No caller portrait or written message.', 'Hold mascot alone with his phone ready to call his mother, facing the viewer for the supported response. Only the sentence stem is written.', 'Mascot smiles gently on the phone and places a plain overnight bag beside the door. Mother\'s reply is heard in narration but she is not depicted. No shopping or extra characters.'],
['In a small laundry shop, the older man hides a sore hand behind a stack of folded shirts. Mascot puts his own bag down and pulls a chair beside the table. No medical aids or diagnosis text.', 'Mascot takes the first shirt from the unfinished pile while uncle changes the hand supporting another shirt. Show a voluntary offer of help through their eye line and posture.', 'Uncle patiently shows mascot how one shirt edge is folded. Their hands are minimal ink shapes; unfinished shirts stay on the same table. No iron, burn, or health claim.', 'Hold uncle and mascot beside the remaining stack of shirts, uncle indicating the workload and mascot listening. Stem stays above, no completed answer.', 'The finished stack is neat. Mascot leaves his own single shirt on the counter, gestures that he will return, and uncle looks up from his chair. No additional customer.'],
['Outside the wrong warehouse door, mascot speaks with the older mustard-shirted cleaner holding a simple broom. The mascot wears no extra shirt or badge with text; only a plain blank work pass.', 'Cleaner points toward the right entrance and picks up the mascot\'s plain dropped pass. Mascot\'s bag is still near his own feet; no writing on the pass.', 'Inside the book warehouse, lavender-shirted female manager indicates one shelf while mascot asks for clarification. Cleaner is absent. Book spines have no writing; no request for a rare named title.', 'Hold mascot beside the shelf with the blank pass visible, ready to describe his new employment. Manager can remain nearby; no cleaner.', 'At the warehouse exit, mascot thanks the cleaner again while holding a plain new shift grid without numbers. Manager is offscreen. Keep the same doorway and both people\'s identities.'],
['At an office-building stairwell, mascot holds a creased plain envelope and asks the mustard-shirted capped security guard for directions. Door above is closed, no building names or floor numbers.', 'Guard points up the staircase while mascot holds the same envelope carefully; modest wet shoe marks, no extra parcel or elevator interfaces.', 'At the lit end of the same corridor, mascot waits by a closed office door, one hand raised to knock. Female office worker stays offscreen until the next opening, no other people.', 'Hold mascot looking for the correct office doorway in the same corridor; show the supported question above without a full answer.', 'Lavender-shirted female office worker opens the door and invites mascot to an empty chair by her desk. His plain envelope has a visibly crumpled corner. Guard is absent.'],
['At a quiet workshop table after the break signal, mascot waits beside the mustard-shirted new colleague who keeps his head down over ordinary unfinished cloth pieces. No busy dangerous machinery or text.', 'Mascot places a plain water cup beside the colleague and pulls out a chair. The colleague looks at the unfinished pile with concern; no physical injury or extreme exhaustion.', 'The colleague slowly removes plain gloves while mascot gestures toward the shaded outdoor bench. Tools remain safely on the worktable, not pulled out of someone\'s hand.', 'Hold both men at the exit to the shaded courtyard, mascot inviting the short break and colleague about to join. Stem only, no countdown.', 'They sit talking on the shaded bench and then turn together toward the workshop entrance. The unfinished work stays inside, suggesting a normal return after the break.'],
['At a laptop desk, mascot hesitates over the send button of a blank generic email window. Mustard-shirted male colleague seated nearby gives a small reassuring nod. No readable mailbox, address or warning banner.', 'Mascot reads his drafted email on the laptop beside a plain travel ticket and bag; colleague listens without pressure. No displayed resignation text or private message.', 'Mascot gently edits the last line in the same generic email window. Keep the screen abstract and blank except approved teaching text, no readable apology letter.', 'Hold mascot with his hand near the laptop touchpad and colleague encouraging him to send. The email remains unsent; show only stem.', 'Mascot has sent the email and now reads a reply on his laptop with a relieved small smile, holding the plain travel ticket beside it. No actual email address or written reply.'],
['At a meeting table with laptop, mascot notices he opened the wrong digital draft. Mustard-shirted Lan sits nearby; others are outside frame. Two simple file icons can be shown without labels or text.', 'Lan moves her chair near mascot and looks with him at the same laptop. A plain older laptop is clearly the source of the mistaken draft; no paper folders, clinic, patient data or named file.', 'Mascot locates the intended digital file in a generic folder view; Lan gestures that there is time. The two simple icons are visually distinct but not readable or labeled.', 'Hold mascot and Lan looking for the digital file on the laptop, with a blank generic folder window. Show the question stem only.', 'Mascot and Lan are alone after the meeting, same laptop open to a simple document page with no readable words. Mascot gives her a small grateful nod; no physical paper case file.'],
['At the workshop lunch doorway, older mustard-shirted newcomer stands with a plain food box. Mascot pulls out the empty chair beside himself. No hard-hat construction hazards or crowd.', 'Earlier that morning, the same newcomer gathers simple overlooked work pieces into a tray while mascot notices. Keep one modest tool/work bench, no trade-specific safety procedure.', 'At the lunch table, mascot points toward the newcomer while answering an unseen colleague about his work. Newcomer holds his food box, posture uncertain; no extra face needed.', 'Hold mascot ready to introduce the nearby newcomer at the same table. The supported sentence stem is above, newcomer in view.', 'Newcomer opens his lunch box and offers mascot one piece of egg with a plain utensil. Both turn slightly toward each other as he begins talking about home. No new characters or text.'],
['At an orchard gate after rain, older mustard-shirted farmer holds an empty simple basket, quiet and lowered shoulders. Mascot puts down his travel bag and follows him toward the orange trees.', 'Among the same trees, a few fallen oranges and broken small branches are visible. Farmer and mascot each use a basket to collect fallen fruit; no pricing, deadline or commerce text.', 'The two sit sorting picked oranges beside the trees in late-morning light, farmer offering to stop for a meal. Show ordinary work and companionship, no scientific harvesting steps.', 'Hold farmer with a small basket and mascot beside him, ready to introduce his occupation. Fruit trees remain visible and stem appears above.', 'Near the house entrance, farmer holds one small orange for mascot and starts peeling it while mascot waits beside the basket. No miraculous recovery of the damaged branches.'],
['At a small model-bridge demonstration table, mustard-shirted female engineer and mascot notice the model is uneven. One simple gray-shirted child watches; no roof, live electrical system or solar panel.', 'Engineer sits at child eye level and gently adjusts a loose model support with her bare simple ink hands. Mascot watches; no measurements, circuitry or actual civil-engineering instructions.', 'Mascot invites the child to call for engineer\'s help when the model leans again. Engineer turns back patiently and lets the child see the small correction.', 'Hold mascot indicating the female engineer beside the tabletop model, with child waiting to try. Only the supported introduction stem is displayed.', 'The model now stands. Engineer gives the child space to try placing one model piece while mascot puts aside a plain printed introduction sheet with no readable writing. No claim that a real bridge is safe.']]
for ep,frames in zip(jobs,visuals):
 p=OUT/'narration-frozen'/f"{ep['job']}.json";e=json.loads(p.read_text());narr_before=[s['narration'] for s in e['scenes']]
 for s,v in zip(e['scenes'],frames):s['visual_en']=v
 if e['job']=='vocab-answer-script-248':
  e['characters'][1]['name_vi']='Anh quản lý';
  for i in [0,2,3,4]:e['scenes'][i]['character_ids']=['CH01']
 if e['job']=='vocab-file-script-254':e['characters'][1]['name_vi']='Lan'
 if e['job']=='vocab-email-script-253':e['characters'][1]['name_vi']='Người đồng nghiệp'
 if e['job']=='vocab-job-script-250':
  e['characters'][1]['name_vi']='Bác lao công';e['characters'].append({'id':'CH03','name_vi':'Chị quản lý','appearance_en':'Adult female minimal ink stick figure, round white face, solid dark oval eyes and a simple tied-back hair silhouette.','outfit_en':'Exactly one plain lavender short-sleeve top and minimal stick limbs.'});e['scenes'][2]['character_ids']=['CH01','CH03'];e['scenes'][3]['character_ids']=['CH01','CH03']
 if e['job']=='vocab-office-script-251':
  e['characters'][1]['name_vi']='Bác bảo vệ';e['characters'][1]['outfit_en']+=' One plain dark cap, no badge.';e['characters'].append({'id':'CH03','name_vi':'Chị trong văn phòng','appearance_en':'Adult female minimal ink stick figure, round white face, solid dark oval eyes and short simple bob hair.','outfit_en':'Exactly one plain lavender short-sleeve top and minimal stick limbs.'});e['scenes'][2]['character_ids']=['CH01'];e['scenes'][3]['character_ids']=['CH01'];e['scenes'][4]['character_ids']=['CH01','CH03']
 if e['job']=='vocab-engineer-script-257':
  e['characters'][1]['name_vi']='Chị kỹ sư';e['characters'].append({'id':'CH03','name_vi':'Em nhỏ','appearance_en':'Small minimal ink stick figure, round white face, solid dark oval eyes and a simple dark hair silhouette.','outfit_en':'Exactly one plain gray short-sleeve top and minimal stick limbs.'})
  for s in e['scenes']:s['character_ids']=['CH01','CH02','CH03']
 assert [s['narration'] for s in e['scenes']]==narr_before;p.write_text(json.dumps(e,ensure_ascii=False,indent=2)+'\n')
# Preserve previously selected specific meanings inside broadly glossed bank entries.
p=OUT/'manifest.json';m=json.loads(p.read_text())
for e in m:
 vocab=e['content']['scenes'][0].get('vocabulary',[]);selected=vocab[0].get('meaning') if vocab else None
 if selected:e['selected_gloss_vi']=selected
 if e['job']=='vocab-file-script-254':
  bpath=Path(e['new_brief_path']);b=json.loads(bpath.read_text());b['planning']['domain_requirements'].append('Nghĩa được chọn ở kịch bản trước của file.n là tập tin trên máy tính; lượt này giữ đúng hướng đó, không đổi sang hồ sơ giấy.');bpath.write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n')
p.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
print('Rewrote all twelve visual plans, actor continuity and preserved digital-file meaning before anchors')
