from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'reports/drama-A1-all-20261001';raw=json.loads((OUT/'narration-attempts/016-027/episodes.json').read_text())['episodes']
frames=[
['At a bakery porch on a rainy day, mascot calls on a plain phone while the older baker looks at trays of bread waiting to be loaded. No visible numbers, food steam claim or crowd.', 'Mascot moves the bread trays further under the porch and listens on the phone; baker stands nearby. Rain is background only, no flooded-road driving instruction.', 'A simple van is parked safely at the porch. The dark-green-shirted capped driver places bread trays side by side with room between them; baker sits down while mascot observes.', 'Hold mascot and baker ready to describe the nearby driver while the driver carefully carries the last tray. Keep van parked and top space clear for the supported line.', 'The driver holds the van door for the baker, then leaves. At the porch, the older baker offers mascot the two small rolls he kept aside. No extra children depicted or promise of speeding.'],
['At a park bench, the small yellow-shirted boy holds mascot\'s hand and notices his red bag is missing. Police officer is not yet seen; no crowd or policing procedure.', 'Mascot and the boy walk slowly toward a plain park help desk. Boy looks at his empty hand and stays beside mascot; no threatening guard or fear-based posture.', 'A dark-navy-shirted female police officer leans slightly toward the boy to listen. The red bag rests on the help desk behind her, visibly the same simple bag as described.', 'Hold all three at the help desk, mascot ready to introduce the kind officer, the boy beginning to speak for himself. No answer beyond approved stem.', 'The boy takes the red bag and checks the small toy inside, then turns back to thank the officer. Mascot gives him room, no dramatic rescue or hug crowd.'],
['At a small sign-painting table, dark-green-shirted Huy closes an old paint box beside an unfinished wooden sign with a simple painted flower. Mascot holds the sign corner to stop it being put away.', 'Huy opens the same paint box again while mascot stays by the unfinished flower. One plain brush, no printer comparison, advertisements or readable business lettering.', 'Mustard-shirted cafe owner looks at the unfinished sign as mascot introduces Huy. Huy speaks about the color with a small open-hand gesture rather than hiding the uneven flower.', 'Hold mascot presenting Huy beside the same paint box and unfinished sign, cafe owner listening. Only the sentence stem is written.', 'Cafe owner gestures that the existing flower should stay. Huy keeps the paint box open and mascot draws his chair closer; no contract, money deposit, miraculous new orders or perfect final design.'],
['Backstage at a modest room stage, mustard-shirted Mai looks down at folded lyrics paper while mascot offers a plain water cup and sits nearby. No readable lyrics or audience crowd.', 'Mai points to a part she remembers on the plain sheet, mascot listens. Curtain stays behind them; do not promise moving mouth or show musical notation/text.', 'Mai tries the remembered phrase while holding a plain microphone, paper folded beside her. Mascot gives a small encouraging nod, no teacher cameo or universal talent claim.', 'Hold mascot ready to introduce Mai near the stage curtain with the sentence stem visible. The announcer is offscreen, no extra person or time countdown.', 'After the modest performance, Mai returns holding the same folded paper and talks to mascot with a slightly relieved expression. No giant applause audience or glowing fame effect.'],
['By a practice-room door, dark-green-shirted Phong repeats a line from a plain script while mascot waits beside him. A small hand mirror is on the table, not broken and not reflecting text.', 'Mascot practices the next line opposite Phong, who gradually looks up from his own face in the mirror. No casting rejection or physical-appearance judgment.', 'Phong puts the mirror into his plain bag and rehearses more slowly with mascot holding the script. Keep one bag and script, no stage costume or extra torso.', 'Hold mascot introducing Phong outside the audition room. The room supervisor may stay offscreen; only the introduction stem is written.', 'Phong comes out with a plain follow-up appointment slip without numbers/text and shows it to mascot. The mirror stays inside his bag. No lead-role award or celebratory crowd.'],
['At grandfather\'s desk, older mustard-shirted grandfather starts closing a drawer while mascot keeps a handwritten plain notebook on the desk. No readable memoir text or quote outside the approved list.', 'Grandfather pulls up a chair and tells mascot about a simple tree visible through the window. Mascot keeps the notebook open and listens rather than waving a publishing offer.', 'Mascot places a fresh plain cover beside the old manuscript, grandfather corrects one simple practice stroke and reaches for a new sheet. No names or extra text.', 'Hold mascot ready to introduce grandfather beside the open manuscript and blank new sheet; grandfather remains at the desk. No completed answer beyond stem.', 'Grandfather writes another non-letter stroke while mascot asks to borrow the manuscript. The drawer remains open, no reporter cameo or automatic book publication.'],
['At a small restaurant kitchen doorway, mascot and mustard-shirted An look at an unattended closed pot and a few plain plates. No hazardous open flame, chef uniform layers or recipe instructions.', 'Mascot receives a simple order from an offscreen customer while An concentrates at the plain counter. No readable menu or food ratios, fewer dishes rather than miraculous speed.', 'An carries the first simple meal to a waiting customer shown only as an offscreen addressee. Mascot gives him space to put it down himself; keep restaurant counter consistent.', 'Hold mascot beside An, ready to identify who cooked this meal. A plain table is set nearby with a single bowl; customer remains offscreen.', 'After the shift, An sits to eat the small meal he kept for himself. Mascot sets the last empty serving tray aside. No tip, medical health claim or sudden promotion.'],
['At a simple street flower cart, mustard-shirted Linh removes a paper ribbon and seems ready to pack. Mascot holds one unfinished bunch, with several unsold flowers plainly visible.', 'Both rearrange flowers quietly while a potential customer has already walked away. Linh looks at a plain small coin pouch, no specific prices, revenue claims or business advice.', 'A lavender-shirted woman pauses by the same flower cart and asks if it returns tomorrow. Mascot answers and Linh shows the bunch she was wrapping, no written address or date.', 'Hold the two sellers beside the still mostly full cart, reflecting a slow business day. The stem is displayed above, no completed answer or empty sold-out cart.', 'The customer leaves with one bunch. Several remain unsold while Linh reties the first paper ribbon and mascot waits beside her. No big advance order or guaranteed future success.'],
['At a modest office after a group picture, mascot stands behind a plain camera looking at a photo that includes colleagues but omits himself. Mustard-shirted Khoa notices the gap. No company logo or text.', 'Khoa points out the missing photographer in the simple photo while mascot shrugs and gets ready to put the camera away. One lavender-shirted coworker is still nearby, no anonymous crowd.', 'Khoa gently pulls mascot toward the empty photo position and sets the camera on a table. The third coworker waits; no head count or clock needed.', 'Hold mascot, Khoa and one coworker in the small office, ready for a supported line about working for this company. Only the stem appears as writing.', 'A new simple photograph includes mascot, Khoa and the coworker together. Mascot keeps both old and new photos on a plain device, showing the personal inclusion without an anniversary banner.'],
['At a home desk, the older mustard-shirted woman holds her hands behind her back and looks uncertainly at a desktop computer. Mascot sits beside her and points to the power button.', 'The woman has pressed the button herself and looks toward mascot for reassurance. A simple family photo thumbnail is planned on the screen, no private messages, names or interface text.', 'The desktop takes a moment to show a plain photo grid while mascot reassures the woman about the old computer. No claim of a diagnosis or guaranteed performance.', 'Hold both beside the desktop and its simple photo grid, showing the supported request to turn on a computer. Avoid the full answer in extra writing.', 'The woman leans closer to the desktop screen and reaches toward the mouse to view another photo. Mascot stays nearby but does not operate it for her; no tears or portrait realism.'],
['Under a bus-stop awning in rain, mustard-shirted Dung gives a closed laptop to mascot to hold securely while she checks her slipping bag strap. One bag, no water touching an open device.', 'Mascot keeps the laptop under the awning while Dung fastens her bag strap. Rain remains beyond the shelter; no countdown, statistics, thesis-grade claim or readable project.', 'The laptop is now safely inside the same bag. Dung releases the bag opening while mascot gestures toward an arriving bus. No display of a second laptop.', 'Hold Dung asking mascot for help with the laptop, with the supported question stem above. Bus stays in the background; no completed answer.', 'At an ordinary classroom presentation table, Dung opens the laptop and looks toward mascot seated nearby before starting. Her bag is now on the floor rather than clutched to her chest. No high-grade result or crowded audience.'],
['In a clinic waiting corridor, older mustard-shirted father stands and sits restlessly while mascot takes a plain phone from a bag and gives it to him. No vital signs, diagnosis, maternity scene or private screen text.', 'Father and mascot sit beside an empty chair, looking toward the closed consultation door. A plain wall clock has no numbers or diagnosis information. Mother remains offscreen.', 'The phone rings as indicated by father looking at it and mascot gesturing toward the handset. Screen stays plain with a small generic call icon, no caller identity or family medical result.', 'Hold mascot inviting father to answer the ringing phone while both remain in the corridor. Stem only, no completed answer.', 'Father listens to the ordinary family call while mascot opens a plain snack box and father shares one small biscuit back. They remain waiting; no medical outcome, baby, treatment or guarantee of recovery.']]
roles=[
[('Bác Năm','older baker','mustard-yellow'),('Bác tài','adult male driver with a small plain cap','dark green')],
[('Cô cảnh sát','adult female police officer with simple tied-back hair and one plain cap','dark navy'),('Bo','small boy with a simple short hair silhouette','yellow')],
[('Huy','adult male painter with a simple short hair silhouette','dark green'),('Bác chủ quán','older cafe owner with a small gray hair silhouette','mustard-yellow')],
[('Mai','young adult female singer with a simple short hair silhouette','mustard-yellow')],
[('Phong','young adult male performer with simple short hair','dark green')],
[('Ông','older male with simple white hair silhouette','mustard-yellow')],
[('An','adult male restaurant cook with a simple small plain cap','mustard-yellow')],
[('Linh','adult female florist with simple tied-back hair','mustard-yellow'),('Người khách','adult female customer with short plain hair','lavender')],
[('Anh Khoa','adult male colleague with simple short hair','mustard-yellow'),('Người đồng nghiệp','adult female colleague with a simple bob','lavender')],
[('Bà','older female with a small simple gray bun','mustard-yellow')],
[('Dung','adult female student with simple tied-back hair','mustard-yellow')],
[('Bố','older male with a simple short gray hair silhouette','mustard-yellow')]]
for orig,states,persons in zip(raw,frames,roles):
 p=OUT/'narration-frozen'/f"{orig['job']}.json";ep=json.loads(p.read_text());before=[s['narration'] for s in ep['scenes']]
 ep['characters']=[orig['characters'][0]]+[{'id':f'CH{i:02}','name_vi':name,'appearance_en':'A minimal ink stick figure, '+appearance+', round white face, solid dark oval eyes and ordinary simple proportions. No realistic muscles or detailed fingers.','outfit_en':'Exactly one plain '+color+' short-sleeve top and minimal stick limbs. Only the explicitly needed small plain role accessory.'} for i,(name,appearance,color) in enumerate(persons,2)]
 ids=[c['id'] for c in ep['characters']]
 for s,visual in zip(ep['scenes'],states):s.update(visual_en=visual,character_ids=ids)
 if orig['job']=='vocab-driver-script-258':
  for i in [0,1,4]:ep['scenes'][i]['character_ids']=['CH01','CH02']
 if orig['job']=='vocab-police-officer-script-259':
  for i in [0,1]:ep['scenes'][i]['character_ids']=['CH01','CH03']
 if orig['job']=='vocab-artist-script-260':
  for i in [0,1]:ep['scenes'][i]['character_ids']=['CH01','CH02']
 if orig['job']=='vocab-business-script-265':
  for i in [0,1,3,4]:ep['scenes'][i]['character_ids']=['CH01','CH02']
 if orig['job']=='vocab-company-script-266':
  # Remove the unnecessary numerical head-count before final narration/anchors freeze.
  ep['scenes'][1]['narration']='Công ty tôi nhỏ, việc chụp ảnh thường tới lượt tôi. Tấm nào tôi cũng chụp giúp rồi lưu lại. Anh Khoa nhìn ảnh mới, hỏi sao lần nào cũng thiếu tôi. Tôi bảo vậy cũng được mà.'
  ep['scenes'][2]['narration']='"Our company is small." Công ty chúng tôi nhỏ. Anh nhìn mấy gương mặt trong ảnh, kéo tôi đứng vào khoảng trống rồi đặt máy lên bàn.'
  ep['plot_vi']='Một công ty nhỏ chụp ảnh cùng nhau; đồng nghiệp nhận ra người chụp luôn vắng trong ảnh và nhường chỗ để người ấy cũng được giữ một kỷ niệm.'
 else:assert [s['narration'] for s in ep['scenes']]==before
 p.write_text(json.dumps(ep,ensure_ascii=False,indent=2)+'\n')
print('Aligned twelve visual/actor plans to final reviewed narration; no unsafe or medical/technical outcome claims')
