from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'reports/drama-A1-all-20261001';raw=json.loads((OUT/'narration-attempts/028-039/episodes.json').read_text())['episodes']
frames=[
['A contextual over-shoulder view at home: older grandfather examines a small phone photo while mascot offers the larger desktop display and moves his chair aside. No dust-based eyesight diagnosis.', 'Mascot opens the same abstract family photo on the larger desktop screen while grandfather looks toward it. Show simple tiny faces only, not extra full mascot torsos or readable interface text.', 'Grandfather points to a tiny hat-wearing face in the desktop photo, recognizing himself. Mascot gives a small confirming nod, no lighting miracle or glowing eyes.', 'Hold both looking at the same desktop display, with grandfather seated near it and the supported sentence stem above. No full answer in extra writing.', 'Grandfather gently stops mascot from moving to the next photo and stays looking at the current image. Keep the large screen and chair positions unchanged, no emotional flourish.'],
['At a print-shop counter, mascot looks at a keyboard that is not entering text; the mustard-shirted woman listens to his request. No spilled food, electronics disassembly or cleaning advice.', 'She slides her own working keyboard toward mascot and sits beside him. One unused keyboard remains to the side, no forceful tapping, tool or loose cables.', 'The older unused keyboard is put aside while mascot begins entering a simple line with the borrowed keyboard. Woman watches patiently; no readable private text or guarantee of repair.', 'Hold mascot ready to ask for use of the nearby woman\'s keyboard, the target device clearly visible and top stem readable. Offscreen customer only.', 'Mascot returns the borrowed keyboard after printing one plain sheet, while the woman remains seated beside him. No readable document, named customer or ink-smell claim.'],
['At a home desk, father moves an unresponsive plain computer mouse while mascot watches. Show the mouse referent in foreground and a generic stationary pointer on screen, no form deadline.', 'Mascot gives father a second working mouse from the neighboring desk while father keeps his own plain notes. No battery-changing instructions or hidden electronic repair.', 'Father now moves the working mouse, corresponding pointer visible in a generic blank window. Mascot moves his chair slightly away to give him control.', 'Hold father\'s hand over the working mouse with mascot beside him, top stem only. Screen has simple shapes, no official form or personal data.', 'Father has clicked a generic confirmation shape, then turns toward mascot to ask for future company. Keep the mouse, plain notes and chairs consistent, no actual government submission text.'],
['At home, mother holds a phone and lightly stops mascot from taking it. Mascot sits nearby and lets her try opening a generic image-sharing app herself. No banking code or money transfer.', 'The phone lies on the table within mother\'s reach; she taps a plain app icon while mascot watches instead of taking over. No address, account data or readable notification.', 'Mother views a simple photo thumbnail and returns toward the phone\'s initial view while mascot indicates one generic close control. No payment confirmation or names.', 'Hold mother ready to open the same app, phone still in her own hands. Show only the supported sentence stem above.', 'Mother is still viewing the photo on her own phone while mascot returns with water. Her posture shows ownership of the task; no printed message or exaggerated happiness.'],
['At a student desk before departure, mascot and Duy look at a simple lesson-file icon in a generic remote webpage. A plain travel bag is nearby. The lesson has not yet been transferred locally.', 'Duy pulls his chair near mascot and indicates the agreed lesson in the same generic page. Mascot pays attention instead of closing the laptop; no copyright/site/account text.', 'At the same fixed desk angle, Duy points to the remotely available lesson icon while mascot asks if it can be downloaded. The local folder on the laptop is still empty.', 'Hold mascot and Duy ready to transfer the lesson from the remote source to the laptop. Show stem only, no complete answer.', 'On a bus seat, mascot opens the now-local lesson on his laptop while Duy asks where to begin. The file icon is inside the local folder; no active-network claim or readable lesson content.'],
['At a home work desk, mascot has just received a family-dinner photo file while mother sits nearby and asks him to save it. The image thumbnail shows small generic faces and a table, no repeated full mascot body.', 'Mascot pauses his current work and looks at the received photo with mother. She waits, pointing to one corner of the image; no private message or clock deadline.', 'At the same desk angle, mascot is about to save the received photo to a recognizable local folder. Mother watches; no actual name or account information on screen.', 'Hold mother and mascot at the same laptop, supported request above and unsaved-versus-saved action not hidden by other text.', 'Mascot reopens the photo from the local folder and turns the laptop toward mother. Both look for one small face in the corner, no guaranteed storage/recovery claim.'],
['At a shared laptop desk, mascot gently stops Tuấn before a class-photo file is removed. The photo icon is visibly distinct from a plain duplicate file; no destructive real UI action or private image.', 'Mascot and Tuấn examine the old photo together in a generic preview, pointing to a tiny figure near its edge. Keep the unwanted duplicate icon beside it, no readable file names.', 'Both have identified a duplicate file and are ready to remove that copy while the original-photo icon remains untouched. Same fixed camera and laptop layout.', 'Hold mascot and Tuấn ready to protect the original photo, with the negative sentence stem above. Original and duplicate remain visually distinct.', 'The duplicate icon is absent but the original photo remains in the same folder. Tuấn turns to ask about the person near the image edge; mascot pulls his chair closer.'],
['At a home desktop, grandmother places then withdraws a finger near the mouse button. Mascot points to a single generic call icon without moving her hand for her.', 'Grandmother moves the pointer toward the generic call button herself. Mascot sits patiently beside her, no realistic fingers or unsupported mouth movement.', 'The call has not connected; a simple green retry icon is visible. Mascot indicates it while grandmother slowly repositions the mouse.', 'Hold grandmother about to click the retry icon, supported stem above and no full answer. Same fixed desk view.', 'Grandmother has started the call herself and speaks toward a generic call window while mascot sits beside her listening. Caller stays a small abstract thumbnail, no real identity or audible-SFX claim.'],
['At a home desk, the young child holds a plain birthday card draft with its name field still blank while mascot brings a keyboard closer. No decorative readable writing.', 'Mascot places a small name-reference card beside the keyboard, letting the child compare instead of typing for her. Use only permitted child-name text if written; no extra alphabet rows.', 'At a fixed desk angle, the child is ready to type the last character in her short name on the generic card interface. Mascot keeps his hands back; no unreadable paragraph.', 'Hold child and mascot near the keyboard, the instruction stem above. The small name field may stay blank, no completed lesson answer.', 'Child keeps the newly printed simple card even though the name is slightly off-center, and puts it in a plain envelope. Mascot remains beside her, no readable address or extra text.'],
['At a student desk, the younger learner has opened a blank document beside an existing list. Mascot pauses her before she types the whole list again. Generic text lines, no readable vocabulary content.', 'Two generic document panels remain side by side: original list on the left, blank target page on the right. Mascot reassures the learner that the original can remain visible.', 'At the same fixed desk angle, learner selects a generic block from the source list with mascot watching. Destination page is still blank, no shortcut keys or interface wording.', 'Hold the learner ready to copy a short block from the source to the blank target page, supported stem above. Do not give the full answer.', 'Learner shows the two populated document panels and confirms the source still exists while mascot returns with water. Same text-block shapes on each side, no account or private school data.'],
['At a small birthday table, mascot and friend wait by a disconnected generic video-call window with a simple cake nearby. No flame, thunder, emergency warning or real internet troubleshooting.', 'Friend holds a plain handwritten card without readable writing while mascot looks for another available room to connect. Cake and closed laptop stay together, no active candle carrying.', 'In friend\'s room, mascot reopens the laptop by an available generic connection icon while friend puts the same cake back on the table. No router/antenna or electrical repair.', 'Hold mascot and friend waiting to connect the birthday call, supported stem above and no exact network address or credentials.', 'The generic birthday video call is connected, with a small abstract distant-family thumbnail. Mascot gestures toward the friend who joined the greeting; cake and laptop unchanged, no extra flame or identity detail.'],
['At a craft room table, the older basket maker places a real small woven basket beside mascot\'s laptop and hesitates to ask if it appears in the communal website. No real URL.', 'Mascot opens a generic website gallery of baskets while the older man points to one distinctive handle. No names, promotional claims or specific village information.', 'The maker recognizes the handle he rewove in a gallery image and tells mascot about it. Mascot pauses the pointer over that thumbnail instead of rushing to another page.', 'Hold the two beside the same generic website gallery and real basket, supported stem above. No full answer or readable navigation labels.', 'The maker brings the real basket forward on the table for a future picture while mascot moves the laptop aside to make room. Show the craft itself taking space, no automatic online publication.']]
roles=[('Ông','older man with short simple white hair'),('Chị Mai','adult female colleague with a simple bob'),('Bố','older man with simple short hair'),('Mẹ','adult woman with a small simple hair bun'),('Duy','adult male friend with simple short hair'),('Mẹ','adult woman with simple tied-back hair'),('Tuấn','adult male friend with simple short hair'),('Bà','older woman with a small gray bun'),('Miu','small child with a simple short hair silhouette'),('Em','younger learner with simple short hair'),('Người bạn','adult friend with simple short hair'),('Bác Hùng','older basket maker with simple short gray hair')]
for orig,states,(name,look) in zip(raw,frames,roles):
 p=OUT/'narration-frozen'/f"{orig['job']}.json";ep=json.loads(p.read_text());before=[s['narration'] for s in ep['scenes']]
 ep['characters']=[orig['characters'][0],{'id':'CH02','name_vi':name,'appearance_en':'Minimal ink stick figure, '+look+', a round white face and solid black oval eyes. Simple proportions and modest expressions, no realistic muscles or fingers.','outfit_en':'Exactly one plain mustard-yellow short-sleeve top and minimal stick limbs; no layered shirt or printed logo.'}]
 for s,v in zip(ep['scenes'],states):s.update(visual_en=v,character_ids=['CH01','CH02'])
 extra={
 'vocab-download-script-274':(2,'Tập tin bắt đầu về máy,', 'Keep the same camera, desk and identities. Show a plain directional transfer arrow from the remote lesson icon toward the laptop local folder, with no percentage or extra text.','Show downloading as movement from a remote source toward the local device.'),
 'vocab-save-script-275':(2,'rồi đặt tên dễ nhận cho ảnh.', 'Keep the same view and laptop. The received-photo thumbnail is now stored inside the chosen local folder; mother and mascot look at the result, no readable filename.','Show the received file becoming stored, rather than merely viewed.'),
 'vocab-delete-script-276':(2,'không bấm ngay như lúc đầu.', 'Keep the same laptop view. The confirmed duplicate icon has been removed while the distinct original-photo icon is still present in its folder. Do not remove the original.','Make the deletion target and preserved original unambiguous.'),
 'vocab-click-script-277':(2,'bà kéo con trỏ chậm hơn lần trước.', 'Keep the same desk and call interface. Grandmother\'s finger presses the mouse button while the pointer is over the single green call-retry icon; no added UI text.','Show the mouse-click action itself at the intended target.'),
 'vocab-type-script-278':(2,'Có một chữ bị lặp, em tự xóa rồi gõ lại,', 'Keep the same keyboard, screen and child. The short name field has acquired typed characters while the child actively presses a key and checks it against the reference card. Only approved child-name text may be used.','Show typed text as the consequence of keyboard input.'),
 'vocab-copy-script-279':(2,'Em lấy một bản vào trang mới,', 'Keep both panels and desk unchanged. The right document now contains the same generic block as the left source, which still remains intact. No real words or keyboard shortcuts.','Show copying preserves the source while adding another instance.')}
 if orig['job'] in extra:
  idx,q,v,reason=extra[orig['job']];assert q in ep['scenes'][idx]['narration'];ep['scenes'][idx]['extra_visual_states']=[{'quote':q,'visual_en':v,'purpose_en':reason}]
 ep['visual_review_ready']=True;assert [s['narration'] for s in ep['scenes']]==before;p.write_text(json.dumps(ep,ensure_ascii=False,indent=2)+'\n')
print('Aligned twelve technology plans; six verbs get explicit same-view before/after beats')
